
import Head from "next/head";
import Menu from "@/components/Menu";

export default function Admin() {

    return (
        <div>
            <Head>
                <title>Admin</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Menu/>
            </main>
        </div>
    )
}