
import Head from "next/head";
import Menu from "@/components/Menu";

import api from '../service/api';
import React, { useState, useEffect } from 'react';
export default function Clients() {

    const [clients, setClients] = useState('');

    useEffect(() => {
      api.get('clients').then(res => {
        setClients(res.data);
      })
    }, []);
    
    return (
        <div>
            <Head>
                <title>Clients</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Menu/>
                <section>
                    <div>
                        {clients && 
                            clients.map((client) =>
                                <>
                                    <div>
                                        {client.id}
                                    </div>
                                    <div>
                                        {client.user_id}
                                    </div>
                                    <div>
                                        {client.name}
                                    </div>
                                    <div>
                                        {client.gender}
                                    </div>
                                    <div>
                                        {client.wage_date}
                                    </div>
                                    <div>
                                        {client.wage_value}
                                    </div>
                                </>
                            )}
                    </div>
                </section>
            </main>
            
        </div>
    )
}