
import Head from "next/head";
import Menu from "@/components/Menu";
import api from '../service/api';
import React, { useState, useEffect } from 'react';
import Card from "@/components/Card";
export default function Clients() {

    const [clients, setClients] = useState('');

    useEffect(() => {
        api.get('clients').then(res => {
            setClients(res.data);
        })
    }, []);

    return (
        <div>
            <Head>
                <title>Clients</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Menu />
                    <section>
                        {clients && clients.map((client) =>
                            <Card id={client.id} name={client.name} gender={client.gender} wage_date={client.wage_date} wage_value={client.wage_value}/>
                        )}
                    </section>
            </main>

        </div>
    )
}