
import Menu from "@/components/Menu";
import Head from "next/head";

export default function Download() {

    return (
        <div>
            <Head>
                <title>Download</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Menu/>
            </main>
        </div>
    )
}