import Button from "../components/Button";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button text="About Us" variant="whiteFilled" />
        <Button text="About Us" variant="blackFilled" />
        <Button text="About Us" variant="outlined" />
        <Button text="About Us" variant="outlinedSecondary" />
        <Button text="About Us" variant="plain" />
      </main>
    </div>
  )
}
