
import Head from "next/head";
import '../styles/Home.module.css';
import Menu from "@/components/Menu";

export default function Resume() {

    return (
        <div>
            <Head>
                <title>Resume</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
            </main>
        </div>
    )
}