import TableComponent from "@/components/Table";
import Head from "next/head";
import styles from '../styles/Resume.module.css';
import Cookies from 'universal-cookie';
import { useEffect, useState } from "react";
import api from '../service/api';
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFilter } from "@fortawesome/free-solid-svg-icons";

export default function Resume() {
    const cookies = new Cookies();
    const [registers, setRegisters] = useState('');

    const headers = ['id', 'Data de Registro', 'Valor', 'Categoria', 'Tipo', 'Ações'];

    const id = cookies.get('client_id');

    useEffect(() => {
        api.get(`register/client/${id}`).then(res => {
            setRegisters(res.data)
        });
    }, []);

    return (
        <div>
            <Head>
                <title>Resume</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className={styles["first-row"]}>
                    <div className={styles["resume-container"]}>
                        <div className={styles["resume-header"]}>
                            Resume
                        </div>
                        <div className={styles["resume-history"]}>
                            {id &&
                                <TableComponent
                                    headers={headers}
                                    datas={registers}
                                    actions={true}
                                >
                                </TableComponent>
                            }
                        </div>
                    </div>
                    <div className={styles["register-container"]}>
                        <Link href="/register">
                            <button className={styles["new-register-btn"]}>
                                Registrar
                            </button>
                        </Link>
                        <div className={styles["resume-graphics"]}>
                            <div className={styles["graphic-filter"]}>
                                <FontAwesomeIcon icon={faFilter}/>
                            </div>
                            <div className={styles["graphic"]}>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles["second-row"]}>
                    <div className={styles["revenue-type-graphics"]}>
                        <div className={styles["revenue-income"]}>

                        </div>
                        <div className={styles["revenue-outcome"]}>

                        </div>
                    </div>
                    <div className={styles["balance"]}>

                    </div>
                </div>
            </main>
        </div>
    )
}
