-- 20220314120003_create_revenue_types_table.sql

CREATE TABLE revenue_types (
  id INT(11) NOT NULL AUTO_INCREMENT,
  type ENUM('income', 'outcome') NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
);