-- 20220314120004_create_logs_table

CREATE TABLE logs (
  id INT(11) NOT NULL AUTO_INCREMENT,
  type ENUM('info', 'warn', 'error') NOT NULL,
  method VARCHAR(255) NOT NULL,
  params TEXT,
  error TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);