
import React, { useState, useEffect } from "react";
import api from '../../service/api';
import { useRouter } from 'next/router';
import Head from "next/head";

export default function Client() {
    const [client, setClient] = useState(null);
    const router = useRouter();
    const { id } = router.query;

    useEffect(() => {
        if (id) {
           api.get(`client/${id}`).then(res => {
              setClient(res.data);
           });
        }
     }, [id]);

    return (
        <div>
            <Head>
                <title>{client && client[0].name}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>{client && client[0].name}</h1>
        </div>
    );
}
